jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: jigglypuff
          password: password
          name: Jigglypuff
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:anonymous"
jobs:
  - script: >
      freeStyleJob('Disk Space Check') {
        steps {
          shell('df')
        }
      }
