jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: chocolateen
          name: Hugo
        - id: vaugie_g
          name: Garance
        - id: i_dont_know
          name: Jeremy
        - id: nasso
          name: Nassim
#  authorizationStrategy:
#   roleBased:
#      roles:
#        global:
#          - name: "admin"
#            description: "Jenkins administrators"
#            permissions:
#              - "Overall/Administer"
#            assignments:
#              - "hugo"
#    globalMatrix:
#      permissions:
#        - "Overall/Administer:admin"
#        - "Overall/Read:anonymous"
jobs:
  diskspace:
    - script: >
        freeStyleJob('Disk Space Check') {
          steps {
            shell('df')
          }
        }
