jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: chocolateen
          name: Hugo
jobs:
  diskspace:
    - script: >
        freeStyleJob('Disk Space Check') {
          steps {
            shell('df')
          }
        }
