jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: chocolateen
          password: ${USER_CHOCOLATEEN_PASSWORD}
          name: Hugo
        - id: vaugie_g
          password: ${USER_VAUGIE_G_PASSWORD}
          name: Garance
        - id: i_dont_know
          password: ${USER_I_DONT_KNOW_PASSWORD}
          name: Jeremy
        - id: nasso
          password: ${USER_NASSO_PASSWORD}
          name: Nassim
  authorizationStrategy: RoleBasedAuthorizationStrategy
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - "hugo"
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:anonymous"
jobs:
  - script: >
      freeStyleJob('Disk Space Check') {
        steps {
          shell('df')
        }
      }
